// import { Geist, Geist_Mono } from "next/font/google";
import { Dongle, Comfortaa } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const dongleSans = Dongle({
  variable: "--font-dongle-sans",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const comfortaaMono = Comfortaa({
  variable: "--font-comfortaa-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dongleSans.variable} ${comfortaaMono.variable} antialiased`}
      >
        {children}
      </body>

      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
    </html>
  );
}
